version: '3.8'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

  loki:
    image: grafana/loki
    ports:
      - 3100:3100

  promtail:
    image: grafana/promtail
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      # - ./promtail/positions.yaml:/var/log/positions.yaml
      - ./promtail/logs:/var/log/access
    environment:
      LOKI: http://loki:3100/loki/api/v1/push
    command:
      - "-config.file=/etc/promtail/config.yml"
      - "-config.expand-env=true"