version: '3.8'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

  loki:
    image: grafana/loki
    volumes:
      - ./loki/config.yml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - ./promtail/logs:/var/log/access
    environment:
      LOKI: http://loki:3100/loki/api/v1/push
      MY_POD_NAME: test
    command:
      - "-config.file=/etc/promtail/config.yml"
      - "-config.expand-env=true"