server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: https://${LOKI}/loki/api/v1/push

target_config:
  sync_period: 10s

scrape_configs:
  - job_name: access-logs
    pipeline_stages:
      - match:
          selector: '{job="access-logs"}'
          pipeline_stages:
            - regex:
                expression: '^(?s)(?P<time>\\S+?) (?P<stream>stdout|stderr) (?P<flags>\\S+?) (?P<content>.*)$'
    decompression:
      enabled: true
      initial_sleep: 10s
      format: gz
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/log/access/*.gz
          job: access-logs