server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: ${LOKI}

target_config:
  sync_period: 10s

scrape_configs:
  - job_name: access-logs
    # pipeline_stages:
    #   - match:
    #       selector: '{job="access-logs"}'
    #       stages:
    #         - labels:
    #             test: filename
    decompression:
      enabled: true
      initial_delay: 10s
      format: gz
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/log/access/*.gz
          podname: ${MY_POD_NAME}
          job: access-logs
    relabel_configs:
      - source_labels: [__path__]
        target_label: pod_file_name
      #   action: replace
      #   regex: '^/var/log/access/test.log.gz$'
      #   replacement: '${1}asdf'
      - source_labels: [podname]
        target_label: test2
      #   action: replace
      #   regex: '^test$'
      #   replacement: '123123_1'
