server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: ${LOKI}

target_config:
  sync_period: 10s

scrape_configs:
  - job_name: access-logs
    pipeline_stages:
      - match:
          selector: '{job="access-logs"}'
          stages:
            - regex:
                #expression: '^(?s)(?P<time>\\S+?) (?P<stream>stdout|stderr) (?P<flags>\\S+?) (?P<content>.*)$'
                expression: '^(?s)(?P<method>\\S+?) (?P<time>\\S+?) (?P<loadbalancer>app/veoh-alb-public/(\S\w+)) ((\S+?) ){9}("(?P<restfulmethod>GET|POST|PUT|PATCH) (?P<protocol>http|https)://(?P<domain>\\S+?):(?P<port>80|443)/(?P<path>\\S+?)\?(?P<parameters>\\S+?) (?P<httpversion>\\S+?)")$'
            - timestamp:
                source: time
                format: 2023-08-10T10:40:00.950980Z00:00
            - labels:
                time:
                method:
                loadbalancer:
                restfulmethod:
                protocol:
                domain:
                port:
                path:
                parameters:
    decompression:
      enabled: true
      initial_delay: 10s
      format: gz
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/log/access/*.gz
          job: access-logs